### ISSUE TITLE
Implement messaging between buyer and seller

### ISSUE THREAD

**Issue by ifeify** [ifeify/campustradein#14]
- [x] **Use Case #1**: Buyer should be able to send seller a message
- [x] **Use Case #2**: Sellers/Users should be able to view all messages in an inbox
- [ ] **Use Case #3**: Seller and Buyer should be able to view a conversation thread about a book
